### ISSUE TITLE
Array of images in schema using "meteor-autoform-file"

### ISSUE THREAD

**Issue by aj07mm** [yogiben/meteor-admin#120]
i have this attribute in my collection:

```
"photoGallery": {
		type: [String],
		label: "Bus - photo gallery",
		optional: true
	}
```

in reality what i want should be this, but it doesnt work:

```
"photo": {
		type: [String],
		label: "Bus - photo",
		optional: false,
		autoform:{
			afFieldInput:{
				type: 'fileUpload',
                collection: 'Images'
			}
		}
	}
```

is there a easy way to do that especially using meteor-admin?
i had to open the package meteor-autoform-file from @yogiben and adapt by hand to suit my purpose.

**Comment by mpowaga** [comment]
This is meteor-autoform-file issue as it doesn't support multiple files per document.

**Comment by johnmarty** [comment]
@aj07mm check out the array of images example about halfway down the page here: https://atmospherejs.com/yogiben/autoform-file

Due to the fact that the existing ProfilePictures collection already uses "images" as a file store, so you'll need to modify this configuration a little bit but hope this helps.
```
Schemas.Posts = new SimpleSchema
  title:
    type: String
    max: 60
 
  pictures:
    type: [String]
    label: 'Choose file' # optional 
 
  "pictures.$":
    autoform:
      afFieldInput:
        type: 'fileUpload',
        collection: 'Images'
``` 

CC: @mpowaga
