### ISSUE TITLE
Template for index page of a collection

### ISSUE THREAD

**Issue by aj07mm** [yogiben/meteor-admin#149]
Is there a way to use another template instead of the default on the index page of a collection(where all data is listed).

In the example i only find reference to "new" and "edit".

```
templates:
              new:
                name: 'postWYSIGEditor'
                data:
                  post: Session.get 'admin_doc' if Meteor.isClient
              edit:
                name: 'postWYSIGEditor'
                data:
                  post: Session.get 'admin_doc' if Meteor.isClient
```
